ALTER TABLE "profiles" DROP CONSTRAINT "profiles_user_id_users_id_fkey", ADD CONSTRAINT "profiles_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "group_members" DROP CONSTRAINT "group_members_username_profiles_username_fkey", ADD CONSTRAINT "group_members_username_profiles_username_fkey" FOREIGN KEY ("username") REFERENCES "profiles"("username") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "group_members" DROP CONSTRAINT "group_members_group_id_groups_id_fkey", ADD CONSTRAINT "group_members_group_id_groups_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "event_confirmations" DROP CONSTRAINT "event_confirmations_group_id_groups_id_fkey", ADD CONSTRAINT "event_confirmations_group_id_groups_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "event_confirmations" DROP CONSTRAINT "event_confirmations_username_profiles_username_fkey", ADD CONSTRAINT "event_confirmations_username_profiles_username_fkey" FOREIGN KEY ("username") REFERENCES "profiles"("username") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "group_events" DROP CONSTRAINT "group_events_group_id_groups_id_fkey", ADD CONSTRAINT "group_events_group_id_groups_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "group_events_final" DROP CONSTRAINT "group_events_final_group_id_groups_id_fkey", ADD CONSTRAINT "group_events_final_group_id_groups_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "group_events_final" DROP CONSTRAINT "group_events_final_plan_id_plans_id_fkey", ADD CONSTRAINT "group_events_final_plan_id_plans_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "plans" DROP CONSTRAINT "plans_group_event_id_group_events_id_fkey", ADD CONSTRAINT "plans_group_event_id_group_events_id_fkey" FOREIGN KEY ("group_event_id") REFERENCES "group_events"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "preferences" DROP CONSTRAINT "preferences_group_event_id_group_events_id_fkey", ADD CONSTRAINT "preferences_group_event_id_group_events_id_fkey" FOREIGN KEY ("group_event_id") REFERENCES "group_events"("id") ON DELETE CASCADE;