# Docker!! yay Based on what i already taught you about docker, you should have a basic idea of what
# this file is doing. But essentially, it just defnies what kind of container we want to get up and
# running.

# Necessary "services" root section
services:
  
  # name of the servuce
  db:
    
    # We are using the official postgres image from dockerhub, this image is configured to run a
    # postgres server on startup and retrieve its configuration from environment variables. Which we
    # define below in the environment section.
    image: postgres:16-alpine

    # name of the container
    container_name: baza_postgres

    # This setting tells docker to automatically restart the container if something goes wrong,
    # unless we explicitly stop it.
    restart: unless-stopped

    # This section defines the environment variables that will be passed to the container when it
    # starts up. If you don't know what env variables are at this point, i suggest you go take a
    # quick peak at what they are on the interwebs. It's a pretty easy concept to grasp and they are
    # everywhere. If you are still curious after doing some research come talk with me.
    environment:
      POSTGRES_USER: postgres # username for the postgres server
      POSTGRES_PASSWORD: postgres # password for the postgres server
      POSTGRES_DB: baza # name of the default database to create when the server starts

    # This section defines the ports that will be exposed by the container. Since we are not running
    # this container in host_mode ("host_mode: true", which means the container will share the same
    # network as the host, your computer in this case), its ports are not automatically exposed and
    # therefore we need to manually set them here. I know it seems kinda confusing but the syntax is
    # pretty simple, every new line is a different mapping between the host and the container. The
    # mapping goes like this: "host_port:container_port". So, for example, "5432:5432" means that
    # port 5432 on our computer (the host) will be mapped to port 5432 inside the container. This
    # means that every network request that we (the host) receive on port 5432, will be forwarded to
    # port 5432 inside the container, and vice versa. It might be a little confusing i know, so if
    # you need help you know where to find me.
    ports:
      - "5432:5432"

    # Volumes are a way to persist data generated by the container, even after the container is
    # stopped or deleted. In this case, we are using a named volume called "baza_db_data" to store
    # the data generated by the postgres server. These volumes are literal directories on your
    # computer that are managed by docker, and can be changed to whatever you want, even local
    # directories (with ./local/path/to/storage:/path/to/container/storage). They can be a little
    # confusing at first, but think of it like this. Whatever is on the left is a folder in your
    # computer, and whatever is on the right is a folder inside the container. All this line does is
    # say "you two are the same thing". If the container writes something to the folder on the
    # right, it will be saved in the folder on the left, and if you put something in the folder on
    # the left, it will be available in the folder on the right.
    volumes:
      - baza_db_data:/var/lib/postgresql/data

# This just defines the name of the volume we are using. basically this is the "let baza_db_data"
# and the part on top is the "baza_db_data = /var/lib/postgresql/data".
volumes:
  baza_db_data: