packages:
  - apps/*
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

strictDepBuilds: false

