$kind: http-example
request:
  url: "{{baseUrl}}/get-access-token"
  method: POST
  headers:
    - key: Content-Type
      value: application/json
    - key: apiKeyCookie
      value: <API Key>
      description: "Added as a part of security scheme: apikey"
  body:
    type: json
    content: |-
      {
        "providerId": "string",
        "accountId": "string",
        "userId": null
      }
response:
  statusCode: 400
  statusText: Bad Request
  body:
    type: text
    content: ""
order: 2000
